name: hangman-app
services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
      - '${WEBSOCKET_SERVER_PORT:-8080}:${WEBSOCKET_SERVER_PORT:-8080}'
    volumes:
      - .:/app
      - /app/node_modules
networks:
  app:
